name: Saludo Personalizado

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: 'Nombre a saludar'
        required: true
        default: 'Mundo'
        type: string

jobs:
  saludar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Saludar persona
      run: echo "Hola ${{ inputs.nombre }}"